apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: x72gp9qnl-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/x72gp9qnl-java-quarkus-gitops